executable              = script.sh
#
# path, runnumber, output folder, events/stream to average, core
#
arguments               = flash/data/LNF 388 flash/analysis/users/mazzitel 1
#
output                  = stdout-$(ClusterId).$(ProcID).txt
error                   = stderr-$(ClusterId).$(ProcID).txt
log                     = output-$(ClusterId).$(ProcID).log
request_cpus            = 8
transfer_executable     = Yes
# file da trasferire, ad esempio l'eseguibile
transfer_input_files    = ../analyze_midas_iq_fft_4ms_paral-pipe.py
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
want_io_proxy           = true
use_oauth_services   = t1
t1_oauth_permissions = profile,email,openid,offline_access
queue
